package actualIAMaybe;

import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class rowerFrame extends javax.swing.JFrame {
    private RandomAccessFile stats;//declares the raf with the rower statistics
    private RandomAccessFile rowers;//declares the raf of rowers (from the createAccount page)
    private RandomAccessFile keyfile;//declares the raf of keys related to rowers
    private RandomAccessFile singleWO;
    String [][] things;
    //int fl = 43;
    public String key;
    DefaultTableModel table;
    public rowerFrame() {
        initComponents();
        table = (DefaultTableModel)personalTable.getModel();
        try{
            stats = new RandomAccessFile ("athleteStats.txt","rw");
            rowers = new RandomAccessFile ("rowers.txt","rw");
            keyfile = new RandomAccessFile ("key.txt","rw");
            singleWO = new RandomAccessFile ("singleDorT.txt","rw");
            things = new holdStuffClass().stuff;
            keyfile.seek(0);
            key = keyfile.readLine();
        }catch(java.io.IOException e){
            System.out.println(e);
        }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        athleteStatsPanel = new javax.swing.JPanel();
        athleteStatsLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        heightField = new javax.swing.JTextField();
        weightField = new javax.swing.JTextField();
        wingspanField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        categoryField = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        twoktimeField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        sixktimeField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        minutewattsField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        ppwattsField = new javax.swing.JTextField();
        logoutButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        trainingEntryPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        singleTimeButton = new javax.swing.JButton();
        intervalsDistanceButton = new javax.swing.JButton();
        intervalsTimeButton = new javax.swing.JButton();
        intervalsVariable = new javax.swing.JButton();
        singleDistanceButton = new javax.swing.JButton();
        testingScoresPanel = new javax.swing.JPanel();
        dataAccessPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        dateFilterButton = new javax.swing.JButton();
        distanceFilterButton = new javax.swing.JButton();
        timeFilterButton = new javax.swing.JButton();
        showAllData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        personalTable = new javax.swing.JTable();
        searchField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel15.setText("•");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jTabbedPane4.setBackground(new java.awt.Color(255, 199, 161));
        jTabbedPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        athleteStatsPanel.setBackground(new java.awt.Color(255, 199, 161));

        athleteStatsLabel.setFont(new java.awt.Font("Osaka", 1, 32)); // NOI18N
        athleteStatsLabel.setText("Athlete Stats");

        jPanel3.setBackground(new java.awt.Color(255, 199, 161));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Physical Attributes"));

        jLabel1.setText("Height (cm):");

        jLabel2.setText("Weight (kg):");

        jLabel3.setText("Racing Category:");

        jLabel4.setText("Wingspan (cm):");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(0, 10, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(heightField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(weightField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(wingspanField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(categoryField)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(heightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(wingspanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 199, 161));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Erg Scores"));

        jLabel5.setText("2k (00:00.0):");

        jLabel23.setText("6k (00:00.0):");

        jLabel24.setText("1 minute (watts):");

        jLabel25.setText("Peak Power (watts):");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel5)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(twoktimeField)
                    .addComponent(sixktimeField)
                    .addComponent(minutewattsField)
                    .addComponent(ppwattsField, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(twoktimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sixktimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(16, 16, 16)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(minutewattsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ppwattsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout athleteStatsPanelLayout = new javax.swing.GroupLayout(athleteStatsPanel);
        athleteStatsPanel.setLayout(athleteStatsPanelLayout);
        athleteStatsPanelLayout.setHorizontalGroup(
            athleteStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, athleteStatsPanelLayout.createSequentialGroup()
                .addGroup(athleteStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(athleteStatsPanelLayout.createSequentialGroup()
                        .addComponent(logoutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, athleteStatsPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(athleteStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(athleteStatsPanelLayout.createSequentialGroup()
                                .addComponent(athleteStatsLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(athleteStatsPanelLayout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(24, 24, 24))
        );
        athleteStatsPanelLayout.setVerticalGroup(
            athleteStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(athleteStatsPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(athleteStatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(athleteStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(athleteStatsPanelLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addGroup(athleteStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logoutButton)
                            .addComponent(updateButton)))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Athlete Stats", athleteStatsPanel);

        trainingEntryPanel.setBackground(new java.awt.Color(255, 102, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel7.setText("Single Distance");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel11.setText("     Single Time");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel12.setText("Intervals: Distance");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel13.setText("     Intervals: Time");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel14.setText("     Intervals: Variable");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addGap(36, 36, 36)
                .addComponent(jLabel11)
                .addGap(35, 35, 35)
                .addComponent(jLabel12)
                .addGap(34, 34, 34)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(24, 24, 24))
        );

        jLabel6.setText("New Workout");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel8.setText("•");

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel16.setText("•");

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel17.setText("•");

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel18.setText("•");

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel19.setText("•");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel16)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel17)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addGap(30, 30, 30))))
        );

        singleTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleTimeButtonActionPerformed(evt);
            }
        });

        singleDistanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleDistanceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(singleTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(intervalsDistanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(intervalsTimeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(intervalsVariable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(singleDistanceButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(singleDistanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(singleTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(intervalsDistanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(intervalsTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(intervalsVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout trainingEntryPanelLayout = new javax.swing.GroupLayout(trainingEntryPanel);
        trainingEntryPanel.setLayout(trainingEntryPanelLayout);
        trainingEntryPanelLayout.setHorizontalGroup(
            trainingEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainingEntryPanelLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        trainingEntryPanelLayout.setVerticalGroup(
            trainingEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainingEntryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Training Entry", trainingEntryPanel);

        javax.swing.GroupLayout testingScoresPanelLayout = new javax.swing.GroupLayout(testingScoresPanel);
        testingScoresPanel.setLayout(testingScoresPanelLayout);
        testingScoresPanelLayout.setHorizontalGroup(
            testingScoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        testingScoresPanelLayout.setVerticalGroup(
            testingScoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Testing Scores", testingScoresPanel);

        jLabel9.setText("Sort by:");

        dateFilterButton.setText("Date");
        dateFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFilterButtonActionPerformed(evt);
            }
        });

        distanceFilterButton.setText("Distance");
        distanceFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distanceFilterButtonActionPerformed(evt);
            }
        });

        timeFilterButton.setText("Time");
        timeFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeFilterButtonActionPerformed(evt);
            }
        });

        showAllData.setText("Show All");
        showAllData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllDataActionPerformed(evt);
            }
        });

        personalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Distance", "Time", "Split"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(personalTable);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Filter by: Date or Distance or Time");

        javax.swing.GroupLayout dataAccessPanelLayout = new javax.swing.GroupLayout(dataAccessPanel);
        dataAccessPanel.setLayout(dataAccessPanelLayout);
        dataAccessPanelLayout.setHorizontalGroup(
            dataAccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataAccessPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataAccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataAccessPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dataAccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(distanceFilterButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(timeFilterButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showAllData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateFilterButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(dataAccessPanelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(dataAccessPanelLayout.createSequentialGroup()
                        .addComponent(searchField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(258, 258, 258))
                    .addGroup(dataAccessPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        dataAccessPanelLayout.setVerticalGroup(
            dataAccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataAccessPanelLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(5, 5, 5)
                .addGroup(dataAccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(dataAccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataAccessPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateFilterButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(distanceFilterButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeFilterButton)
                        .addGap(146, 146, 146)
                        .addComponent(showAllData)
                        .addGap(17, 17, 17))
                    .addGroup(dataAccessPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jTabbedPane4.addTab("Data Access", dataAccessPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String key;
        String twok = fixtime(twoktimeField.getText());
        String sixk = fixtime(sixktimeField.getText());
        try {
            keyfile.seek(0);
            key = keyfile.readLine();
            setraf(key,heightField.getText(),weightField.getText(),wingspanField.getText(),categoryField.getText(), twok,sixk, minutewattsField.getText(),ppwattsField.getText());
        } catch (IOException ex) {
            Logger.getLogger(rowerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        IAframe frame1 = new IAframe();
        frame1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void singleDistanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleDistanceButtonActionPerformed
        entryWindow1 frame1 = new entryWindow1();
        frame1.setVisible(true);
        frame1.jLabel1.setText("Single Distance");
        this.setVisible(false);
    }//GEN-LAST:event_singleDistanceButtonActionPerformed

    private void singleTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleTimeButtonActionPerformed
       entryWindow1 frame1 = new entryWindow1();
       frame1.setVisible(true);
       frame1.jLabel1.setText("Single Time");
       this.setVisible(false);
    }//GEN-LAST:event_singleTimeButtonActionPerformed

    private String [][] godArray(){
        ArrayList<String> posn = new ArrayList<>();
        String record = "";
            int count = 0;
            int i = 0;
        try {
            while((i*285)<singleWO.length()){
                singleWO.seek(i*285);
                String temp = singleWO.readLine().substring(0,3);
                if(key.equals(temp)){
                    count++;
                    posn.add(String.valueOf(i));
                    System.out.println(temp);
                    System.out.println(i);
                }
                i++;
            }
        } catch (IOException ex) {
            Logger.getLogger(rowerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            String [] nums = posn.toArray(new String[posn.size()]);
            String [][] workouts  = new String [count][4];
            for (int j = 0; j < count; j++) {
            try {
                singleWO.seek(Integer.valueOf(nums[j])*285);
                record = singleWO.readLine();
                workouts[j][0] = record.substring(4,14);
                workouts[j][1] = stripString(record.substring(14,20));
                workouts[j][2] = stripString(record.substring(20,27));
                workouts[j][3] = stripString(record.substring(27,34)); 
            } catch (IOException ex) {
                Logger.getLogger(rowerFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
            return workouts;
    }
    private void showAllDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllDataActionPerformed
        table.setRowCount(0);
        String [][] workouts = godArray();
        for (int j = 0; j < workouts.length; j++) {
            table.insertRow(table.getRowCount(), new String[]{workouts[j][0],workouts[j][1],workouts[j][2],workouts[j][3]});
        }
    }//GEN-LAST:event_showAllDataActionPerformed

    private void distanceFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distanceFilterButtonActionPerformed
        table.setRowCount(0);
        String [][] workouts = godArray();
        int arraySize = workouts.length;
        int [] byDistance = new int [arraySize];
        for (int i = 0; i < byDistance.length; i++) {
            byDistance[i] = i;
        }
        int temp;
        for (int i = 0; i < workouts.length-1; i++) {
            for (int j = i+1; j < workouts.length; j++) {
                if(Integer.parseInt(workouts[byDistance[i]][1]) > Integer.parseInt(workouts[byDistance[j]][1])){
                    temp = byDistance[i];
                    byDistance[i] = byDistance[j];
                    byDistance[j] = temp;
            }
        }
        }
        for (int j = 0; j < workouts.length; j++) {
            table.insertRow(table.getRowCount(), new String[]{workouts[byDistance[j]][0],workouts[byDistance[j]][1],workouts[byDistance[j]][2],workouts[byDistance[j]][3]});
        }
    }//GEN-LAST:event_distanceFilterButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dateFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFilterButtonActionPerformed
       table.setRowCount(0);
        String [][] workouts = godArray();
        int [] byDate = new int [workouts.length];
        for (int i = 0; i < byDate.length; i++) {
            byDate[i] = i;
        }
        int temp;
        for (int i = 0; i < workouts.length-1; i++) {
            for (int j = i+1; j < workouts.length; j++) {
                if(fixDate(workouts[byDate[i]][0]) > fixDate(workouts[byDate[j]][0])){
                    temp = byDate[i];
                    byDate[i] = byDate[j];
                    byDate[j] = temp;
            }
        }
        }
        for (int j = 0; j < workouts.length; j++) {
            table.insertRow(table.getRowCount(), new String[]{workouts[byDate[j]][0],workouts[byDate[j]][1],workouts[byDate[j]][2],workouts[byDate[j]][3]});
        }
    }//GEN-LAST:event_dateFilterButtonActionPerformed

    private void timeFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeFilterButtonActionPerformed
         table.setRowCount(0);
        String [][] workouts = godArray();
        int [] byTime = new int [workouts.length];
        for (int i = 0; i < byTime.length; i++) {
            byTime[i] = i;
        }
        int temp;
        for (int i = 0; i < workouts.length-1; i++) {
            for (int j = i+1; j < workouts.length; j++) {
                if(fixTime(workouts[byTime[i]][2]) > fixTime(workouts[byTime[j]][2])){
                    temp = byTime[i];
                    byTime[i] = byTime[j];
                    byTime[j] = temp;
            }
        }
        }
        for (int j = 0; j < workouts.length; j++) {
            table.insertRow(table.getRowCount(), new String[]{workouts[byTime[j]][0],workouts[byTime[j]][1],workouts[byTime[j]][2],workouts[byTime[j]][3]});
        }
    }//GEN-LAST:event_timeFilterButtonActionPerformed
    private int fixTime(String string){
        int doneInt = 0;
        doneInt += (Integer.parseInt(string.substring(0,2)))*1000;
        doneInt += (Integer.parseInt(string.substring(3,5)))*10;
        doneInt += (Integer.parseInt(string.substring(6)));
        System.out.println(doneInt);
        return doneInt;
    }
    private int fixDate(String string){
        int doneInt = 0;
        doneInt += (Integer.parseInt(string.substring(6)))*10000;
        doneInt += (Integer.parseInt(string.substring(3,5)))*100;
        doneInt += (Integer.parseInt(string.substring(0,2)));
        return doneInt;
    }
    private String stripString(String string){
        String doneString = "";
        for (int i = 0; i < string.length(); i++) {
            if(string.charAt(i) != 'x'){
                doneString+=string.charAt(i);
            }
        }
        return doneString;
    }   
    private String fixtime(String string){
        String donetime = "";
        String temp = "";
        if(string.charAt(1)==':'){
            temp +=0;
        }
        temp += string;
        double time = 60;
        time = time*Integer.parseInt(temp.substring(0,2));
        time += Integer.parseInt(temp.substring(3,5));
        time += 0.1*Integer.parseInt(temp.substring(6));
        System.out.println("time in seconds " + time);
        donetime = String.valueOf(time);
        return donetime;
    }
    private void setraf(String key, String height, String weight, String wingspan, String category, String twok, String sixk, String onem, String ppow){
        try {
            String fullrecord = "";
            fullrecord += key+padtext(height,3)+padtext(weight,3)+padtext(wingspan,3)+padtext(category,11)+padtext(twok,5)+padtext(sixk,6)+padtext(onem,4)+padtext(ppow,4)+"\n";
            int statkey = Integer.parseInt(key);
            stats.seek(statkey*43);
            stats.writeBytes(fullrecord);
                } catch (IOException ex) {
            Logger.getLogger(rowerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private String padtext(String string, int length){
        int add = length - string.length();
        for (int i = 0; i < add; i++) {
            string += 'x';
        }
        return string;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rowerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rowerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rowerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rowerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rowerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel athleteStatsLabel;
    private javax.swing.JPanel athleteStatsPanel;
    public javax.swing.JTextField categoryField;
    private javax.swing.JPanel dataAccessPanel;
    private javax.swing.JButton dateFilterButton;
    private javax.swing.JButton distanceFilterButton;
    public javax.swing.JTextField heightField;
    private javax.swing.JButton intervalsDistanceButton;
    private javax.swing.JButton intervalsTimeButton;
    private javax.swing.JButton intervalsVariable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JButton logoutButton;
    public javax.swing.JTextField minutewattsField;
    private javax.swing.JTable personalTable;
    public javax.swing.JTextField ppwattsField;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton showAllData;
    private javax.swing.JButton singleDistanceButton;
    private javax.swing.JButton singleTimeButton;
    public javax.swing.JTextField sixktimeField;
    private javax.swing.JPanel testingScoresPanel;
    private javax.swing.JButton timeFilterButton;
    private javax.swing.JPanel trainingEntryPanel;
    public javax.swing.JTextField twoktimeField;
    private javax.swing.JButton updateButton;
    public javax.swing.JTextField weightField;
    public javax.swing.JTextField wingspanField;
    // End of variables declaration//GEN-END:variables
}
